Repository no-nangbie/backend, pull requests merged in 2024-09, with the labels that each got.

#4 feat:#3 Auditable 구현
  src/main/java/com/nonangbie/audit/Auditable.java
Labels: enhancement

#7 feat:#5 필요한 공통 package추가
  src/main/java/com/nonangbie/advice/GlobalExceptionAdvice.java
  src/main/java/com/nonangbie/errorResponse/ErrorResponse.java
Labels: enhancement

#10 feat:#9 github action setting
  .github/workflows/main.yml
Labels: enhancement

#11 Feat/food
  .github/workflows/main.yml
  build.gradle
  src/main/java/com/nonangbie/exception/ExceptionCode.java
  src/main/java/com/nonangbie/food/controller/FoodController.java
  src/main/java/com/nonangbie/food/dto/FoodDto.java
  src/main/java/com/nonangbie/food/entity/Food.java
  src/main/java/com/nonangbie/food/mapper/FoodMapper.java
  src/main/java/com/nonangbie/food/repository/FoodRepository.java
  src/main/java/com/nonangbie/food/service/FoodService.java
Labels: enhancement

#12 fix:#9 docker workflows fix
  .github/workflows/main.yml
Labels: bug

#13 fix:#9 docker workflows fix
  .github/workflows/main.yml
Labels: bug

#15 fix:#9 Dockerfile added
  Dockerfile
Labels: bug

#17 Feat/menu
  src/main/java/com/nonangbie/exception/ExceptionCode.java
  src/main/java/com/nonangbie/menu/controller/MenuController.java
  src/main/java/com/nonangbie/menu/dto/MenuDto.java
  src/main/java/com/nonangbie/menu/entity/Menu.java
  src/main/java/com/nonangbie/menu/mapper/MenuMapper.java
  src/main/java/com/nonangbie/menu/reposiitory/MenuRepository.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
Labels: enhancement

#22 feat:#19 Member패키지 구현
  src/main/java/com/nonangbie/member/controller/MemberController.java
  src/main/java/com/nonangbie/member/dto/MemberDto.java
  src/main/java/com/nonangbie/member/dto/PasswordMatches.java
  src/main/java/com/nonangbie/member/dto/PasswordMatchesValidator.java
  src/main/java/com/nonangbie/member/dto/VerificationRequest.java
  src/main/java/com/nonangbie/member/entity/Member.java
  src/main/java/com/nonangbie/member/mapper/MemberMapper.java
  src/main/java/com/nonangbie/member/repository/MemberRepository.java
  src/main/java/com/nonangbie/member/service/MemberService.java
Labels: enhancement

#26 feat:#20 EventListener 구현
  src/main/java/com/nonangbie/eventListener/CustomEvent.java
  src/main/java/com/nonangbie/eventListener/EventCaseEnum.java
  src/main/java/com/nonangbie/eventListener/ServiceEventListener.java
Labels: enhancement

#27 feat:#21 Switched DataBase H2 -> Mysql
  build.gradle
Labels: enhancement

#32 Fix/merge fix
  src/main/java/com/nonangbie/exception/ExceptionCode.java
  src/main/java/com/nonangbie/menu/dto/MenuDto.java
Labels: bug

#33 feat:#31 Board 구현
  src/main/java/com/nonangbie/board/controller/BoardController.java
  src/main/java/com/nonangbie/board/dto/BoardDto.java
  src/main/java/com/nonangbie/board/entity/Board.java
  src/main/java/com/nonangbie/board/mapper/BoardMapper.java
  src/main/java/com/nonangbie/board/repository/BoardRepository.java
  src/main/java/com/nonangbie/board/service/BoardService.java
  src/main/java/com/nonangbie/exception/ExceptionCode.java
  src/main/java/com/nonangbie/member/entity/Member.java
  src/main/java/com/nonangbie/member/repository/MemberRepository.java
Labels: enhancement

#37 fix:#36 security build failed fix
  build.gradle
  src/main/java/com/nonangbie/member/controller/MemberController.java
Labels: bug

#42 feat:#41 boardlike 구현
  build.gradle
  src/main/java/com/nonangbie/board/entity/Board.java
  src/main/java/com/nonangbie/board/service/BoardService.java
  src/main/java/com/nonangbie/boardLike/entity/BoardLike.java
  src/main/java/com/nonangbie/boardLike/repository/BoardLikeRepository.java
Labels: enhancement

#44 feat: #43 Member_food 테이블 생성
  src/main/java/com/nonangbie/exception/ExceptionCode.java
  src/main/java/com/nonangbie/food/entity/Food.java
  src/main/java/com/nonangbie/memberFood/controller/MemberFoodController.java
  src/main/java/com/nonangbie/memberFood/dto/MemberFoodDto.java
  src/main/java/com/nonangbie/memberFood/entity/MemberFood.java
  src/main/java/com/nonangbie/memberFood/mapper/MemberFoodMapper.java
  src/main/java/com/nonangbie/memberFood/repository/MemberFoodRepository.java
  src/main/java/com/nonangbie/memberFood/service/MemberFoodService.java
Labels: enhancement

#47 fix: #46 MenuMapper, FoodMenu Mapper 수정
  src/main/java/com/nonangbie/foodMenu/controller/FoodMenuController.java
  src/main/java/com/nonangbie/foodMenu/dto/FoodMenuDto.java
  src/main/java/com/nonangbie/foodMenu/mapper/FoodMenuMapper.java
  src/main/java/com/nonangbie/menu/entity/Menu.java
  src/main/java/com/nonangbie/menu/mapper/MenuMapper.java
Labels: enhancement

#50 fix: #49 Member_Food TEST
  src/main/java/com/nonangbie/food/repository/FoodRepository.java
  src/main/java/com/nonangbie/memberFood/controller/MemberFoodController.java
  src/main/java/com/nonangbie/memberFood/dto/MemberFoodDto.java
  src/main/java/com/nonangbie/memberFood/mapper/MemberFoodMapper.java
  src/main/java/com/nonangbie/memberFood/repository/MemberFoodRepository.java
  src/main/java/com/nonangbie/memberFood/service/MemberFoodService.java
Labels: enhancement

#51 feat:#36 시큐리티,로그인,이메일 인증 구현
  build.gradle
  src/main/java/com/nonangbie/auth/controller/AuthController.java
  src/main/java/com/nonangbie/auth/dto/LoginDto.java
  src/main/java/com/nonangbie/auth/dto/RedisProperties.java
  src/main/java/com/nonangbie/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/nonangbie/auth/filter/JwtVerificationFilter.java
  src/main/java/com/nonangbie/auth/handler/MemberAccessDeniedHandler.java
  src/main/java/com/nonangbie/auth/handler/MemberAuthenticationEntryPoint.java
  src/main/java/com/nonangbie/auth/handler/MemberAuthenticationFailureHandler.java
  src/main/java/com/nonangbie/auth/handler/MemberAuthenticationSuccessHandler.java
  src/main/java/com/nonangbie/auth/jwt/JwtTokenizer.java
  src/main/java/com/nonangbie/auth/service/AuthService.java
  src/main/java/com/nonangbie/auth/userdetails/MemberDetailsService.java
  src/main/java/com/nonangbie/auth/utils/CustomAuthorityUtils.java
  src/main/java/com/nonangbie/auth/utils/ErrorResponder.java
  src/main/java/com/nonangbie/config/SecurityConfiguration.java
  src/main/java/com/nonangbie/email/config/EmailConfig.java
  src/main/java/com/nonangbie/email/service/EmailVerificationService.java
  src/main/java/com/nonangbie/email/tool/EmailTool.java
  src/main/java/com/nonangbie/exception/ExceptionCode.java
  src/main/java/com/nonangbie/member/controller/MemberController.java
  src/main/java/com/nonangbie/member/dto/MemberDto.java
  src/main/java/com/nonangbie/member/entity/Member.java
  src/main/java/com/nonangbie/member/service/MemberService.java
  src/main/java/com/nonangbie/redis/config/RedisConfig.java
  src/main/java/com/nonangbie/redis/tool/RedisTool.java
Labels: enhancement

#54 feat:#52 abstract class ExtractMemberEmail Added
  src/main/java/com/nonangbie/member/service/MemberService.java
  src/main/java/com/nonangbie/utils/ExtractMemberEmail.java
Labels: enhancement

#56 feat:#31 Board Authentication
  src/main/java/com/nonangbie/board/dto/BoardDto.java
  src/main/java/com/nonangbie/board/service/BoardService.java
Labels: enhancement

#58 feat:#57 Food Authentication 적용
  src/main/java/com/nonangbie/board/controller/BoardController.java
  src/main/java/com/nonangbie/exception/ExceptionCode.java
  src/main/java/com/nonangbie/food/controller/FoodController.java
  src/main/java/com/nonangbie/food/entity/Food.java
  src/main/java/com/nonangbie/food/service/FoodService.java
  src/main/java/com/nonangbie/utils/ExtractMemberEmail.java
Labels: enhancement

#59 fix:#31 Board Get Method Bug Fix
  src/main/java/com/nonangbie/board/controller/BoardController.java
  src/main/java/com/nonangbie/board/dto/BoardDto.java
  src/main/java/com/nonangbie/board/mapper/BoardMapper.java
  src/main/java/com/nonangbie/board/service/BoardService.java
Labels: bug, enhancement

#60 feat:#57 Food, foodMenu Authentication 적용
  src/main/java/com/nonangbie/food/entity/Food.java
  src/main/java/com/nonangbie/food/service/FoodService.java
  src/main/java/com/nonangbie/foodMenu/controller/FoodMenuController.java
  src/main/java/com/nonangbie/foodMenu/entity/FoodMenu.java
  src/main/java/com/nonangbie/foodMenu/service/FoodMenuService.java
  src/main/java/com/nonangbie/memberFood/controller/MemberFoodController.java
Labels: enhancement

#61 fix: #35 메뉴, 게시판 eneity 수정
  src/main/java/com/nonangbie/WebConfig.java
  src/main/java/com/nonangbie/board/entity/Board.java
  src/main/java/com/nonangbie/menu/entity/Menu.java
Labels: enhancement

#63 feat:#57 MemberFood Authentication 적용
  src/main/java/com/nonangbie/board/service/BoardService.java
  src/main/java/com/nonangbie/memberFood/controller/MemberFoodController.java
  src/main/java/com/nonangbie/memberFood/entity/MemberFood.java
  src/main/java/com/nonangbie/memberFood/service/MemberFoodService.java
Labels: enhancement

#64 fix: #36 시큐리티 수정
  src/main/java/com/nonangbie/WebConfig.java
  src/main/java/com/nonangbie/config/SecurityConfiguration.java
Labels: enhancement

#66 feat:65 Menu Authentication 적용
  src/main/java/com/nonangbie/menu/controller/MenuController.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
Labels: enhancement

#67 fix:#36 extractmemberemail 변수명 수정
  src/main/java/com/nonangbie/utils/ExtractMemberEmail.java
Labels: enhancement

#68 fix: #43 MemberFood 수정
  src/main/java/com/nonangbie/memberFood/controller/MemberFoodController.java
  src/main/java/com/nonangbie/memberFood/service/MemberFoodService.java
Labels: enhancement

#69 fix:#31 board Controller & Service pagenation bug fix
  src/main/java/com/nonangbie/board/controller/BoardController.java
  src/main/java/com/nonangbie/board/repository/BoardRepository.java
  src/main/java/com/nonangbie/board/service/BoardService.java
Labels: bug

#72 fix:#31 board LikeCheck Method Added & Like api Changed
  src/main/java/com/nonangbie/board/controller/BoardController.java
  src/main/java/com/nonangbie/board/dto/BoardDto.java
  src/main/java/com/nonangbie/board/mapper/BoardMapper.java
  src/main/java/com/nonangbie/board/service/BoardService.java
  src/main/java/com/nonangbie/boardLike/repository/BoardLikeRepository.java
  src/main/java/com/nonangbie/config/SecurityConfiguration.java
Labels: bug, enhancement

#79 fix : #43 MemberFood 수정
  src/main/java/com/nonangbie/memberFood/entity/MemberFood.java
  src/main/java/com/nonangbie/memberFood/service/MemberFoodService.java
Labels: enhancement

#81 fix: #43 MemberFood 수정
  src/main/java/com/nonangbie/memberFood/repository/MemberFoodRepository.java
  src/main/java/com/nonangbie/memberFood/service/MemberFoodService.java
Labels: enhancement

#85 Feat/aws s3
  build.gradle
  src/main/java/com/nonangbie/S3/config/S3Config.java
  src/main/java/com/nonangbie/S3/service/S3Uploader.java
  src/main/java/com/nonangbie/board/controller/BoardController.java
  src/main/java/com/nonangbie/board/dto/BoardDto.java
  src/main/java/com/nonangbie/board/service/BoardService.java
Labels: bug, enhancement

#87 fix: #86 MemberFood, SecurityConfiguration 수정
  src/main/java/com/nonangbie/config/SecurityConfiguration.java
  src/main/java/com/nonangbie/memberFood/service/MemberFoodService.java
Labels: enhancement

#89 [BE] Recipe Like dev
  src/main/java/com/nonangbie/member/entity/Member.java
  src/main/java/com/nonangbie/menu/controller/MenuController.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
  src/main/java/com/nonangbie/menuLike/entity/MenuLike.java
  src/main/java/com/nonangbie/menuLike/repository/MenuLikeRepository.java
Labels: bug, enhancement

#90 feat/#88 Recipe Like Send to FE dev
  src/main/java/com/nonangbie/menu/controller/MenuController.java
  src/main/java/com/nonangbie/menu/dto/MenuDto.java
  src/main/java/com/nonangbie/menu/mapper/MenuMapper.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
Labels: bug, enhancement

#91 fix: #40 미보유 재료 수량 추가
  src/main/java/com/nonangbie/menu/controller/MenuController.java
  src/main/java/com/nonangbie/menu/dto/MenuDto.java
  src/main/java/com/nonangbie/menu/entity/Menu.java
  src/main/java/com/nonangbie/menu/mapper/MenuMapper.java
Labels: enhancement

#92 fix: #43 냉장고 초기화
  src/main/java/com/nonangbie/memberFood/controller/MemberFoodController.java
  src/main/java/com/nonangbie/memberFood/repository/MemberFoodRepository.java
  src/main/java/com/nonangbie/memberFood/service/MemberFoodService.java
Labels: enhancement

#93 fix:#31 작성자 이메일 정보 response Dto에 추가
  src/main/java/com/nonangbie/board/dto/BoardDto.java
  src/main/java/com/nonangbie/board/mapper/BoardMapper.java
Labels: enhancement

#94 fix:#21 sql Data 삽입이상 fix
  src/main/resources/data.sql
Labels: bug

#95 feat:#82 Board Patch 기능 및 S3 파일 업데이트 설정
  src/main/java/com/nonangbie/S3/service/S3Uploader.java
  src/main/java/com/nonangbie/board/controller/BoardController.java
  src/main/java/com/nonangbie/board/dto/BoardDto.java
  src/main/java/com/nonangbie/board/service/BoardService.java
  src/main/java/com/nonangbie/exception/ExceptionCode.java
  src/main/java/com/nonangbie/utils/ExtractMemberEmail.java
Labels: bug, enhancement

#96 fix: #25 메뉴 좋아요 조회
  src/main/java/com/nonangbie/menu/controller/MenuController.java
  src/main/java/com/nonangbie/menu/mapper/MenuMapper.java
Labels: enhancement

#97 feat:#21 Menu & Food DB 추가
  src/main/java/com/nonangbie/menu/entity/Menu.java
  src/main/resources/data.sql
Labels: enhancement

#98 feat:#21 sql Image Data Added
  src/main/resources/data.sql
Labels: enhancement

#99 feat:#88 레시피 사진 전송
  src/main/java/com/nonangbie/menu/dto/MenuDto.java
  src/main/java/com/nonangbie/menu/mapper/MenuMapper.java
Labels: enhancement

#101 feat:#31 board 좋아요 리스트 필터 추가
  src/main/java/com/nonangbie/board/controller/BoardController.java
  src/main/java/com/nonangbie/board/dto/BoardDto.java
  src/main/java/com/nonangbie/board/mapper/BoardMapper.java
  src/main/java/com/nonangbie/board/repository/BoardRepository.java
  src/main/java/com/nonangbie/board/service/BoardService.java
  src/main/java/com/nonangbie/boardLike/repository/BoardLikeRepository.java
Labels: enhancement

#107 feat:#106 Statistics 기본 틀 구현 50%
  src/main/java/com/nonangbie/exception/ExceptionCode.java
  src/main/java/com/nonangbie/member/entity/Member.java
  src/main/java/com/nonangbie/menu/repository/MenuRepository.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
  src/main/java/com/nonangbie/statistics/controller/StatisticsController.java
  src/main/java/com/nonangbie/statistics/entity/Statistics.java
  src/main/java/com/nonangbie/statistics/repository/StatisticsRepository.java
  src/main/java/com/nonangbie/statistics/service/StatisticsService.java
Labels: enhancement

#109 feat:#21 Menu & Food DB 추가
  src/main/resources/data.sql
Labels: enhancement

#110 Feat/board
  src/main/java/com/nonangbie/board/controller/BoardController.java
  src/main/java/com/nonangbie/board/entity/Board.java
  src/main/java/com/nonangbie/board/repository/BoardRepository.java
  src/main/java/com/nonangbie/board/service/BoardService.java
  src/main/java/com/nonangbie/exception/ExceptionCode.java
  src/main/java/com/nonangbie/memberMenuCategory/entity/MemberMenuCategory.java
  src/main/java/com/nonangbie/memberMenuCategory/repository/MemberMenuCategoryRepository.java
  src/main/java/com/nonangbie/memberMenuCategory/service/MemberMenuCategoryService.java
  src/main/java/com/nonangbie/menuCategory/entity/MenuCategory.java
  src/main/java/com/nonangbie/menuCategory/init/DataInitializer.java
  src/main/java/com/nonangbie/menuCategory/repository/MenuCategoryRepository.java
Labels: bug, enhancement

#111 feat:#106 전체적인 통계 소스 구조 변경 및 join & enum 테이블 생성
  src/main/java/com/nonangbie/enumData/entity/MenuCategory.java
  src/main/java/com/nonangbie/enumData/entity/MenuCookTime.java
  src/main/java/com/nonangbie/enumData/entity/MenuDifficulty.java
  src/main/java/com/nonangbie/enumData/init/DataInitializer.java
  src/main/java/com/nonangbie/enumData/repository/MenuCategoryRepository.java
  src/main/java/com/nonangbie/enumData/repository/MenuCookTimeRepository.java
  src/main/java/com/nonangbie/enumData/repository/MenuDifficultyRepository.java
  src/main/java/com/nonangbie/member/entity/Member.java
  src/main/java/com/nonangbie/member/service/MemberService.java
  src/main/java/com/nonangbie/memberMenuCategory/entity/MemberMenuCategory.java
  src/main/java/com/nonangbie/memberMenuCategory/repository/MemberMenuCategoryRepository.java
  src/main/java/com/nonangbie/memberMenuCategory/service/MemberMenuCategoryService.java
  src/main/java/com/nonangbie/menuCategory/init/DataInitializer.java
  src/main/java/com/nonangbie/statistics/controller/StatisticsController.java
  src/main/java/com/nonangbie/statistics/entity/Statistics.java
  src/main/java/com/nonangbie/statistics/repository/StatisticsRepository.java
  src/main/java/com/nonangbie/statistics/service/StatisticsService.java
Labels: enhancement

#112 feat:#106 통계 정보 수집 구현
  src/main/java/com/nonangbie/enumData/init/DataInitializer.java
  src/main/java/com/nonangbie/statistics/controller/StatisticsController.java
  src/main/java/com/nonangbie/statistics/repository/StatisticsRepository.java
  src/main/java/com/nonangbie/statistics/service/StatisticsService.java
Labels: enhancement

#113 fix: #19 Member 수정
  src/main/java/com/nonangbie/member/controller/MemberController.java
  src/main/java/com/nonangbie/member/dto/MemberDto.java
  src/main/java/com/nonangbie/member/mapper/MemberMapper.java
  src/main/java/com/nonangbie/member/service/MemberService.java
Labels: enhancement

#114 feat:#106 통계 항목 추가 및 fridge 항목 추가에 따른 통계 수집
  src/main/java/com/nonangbie/eventListener/CustomEvent.java
  src/main/java/com/nonangbie/eventListener/EventCaseEnum.java
  src/main/java/com/nonangbie/eventListener/ServiceEventListener.java
  src/main/java/com/nonangbie/memberFood/controller/MemberFoodController.java
  src/main/java/com/nonangbie/memberFood/service/MemberFoodService.java
  src/main/java/com/nonangbie/statistics/controller/StatisticsController.java
  src/main/java/com/nonangbie/statistics/entity/Statistics.java
  src/main/java/com/nonangbie/statistics/repository/StatisticsRepository.java
  src/main/java/com/nonangbie/statistics/service/StatisticsService.java
Labels: enhancement

#116 feat:#115 닉네임 변경 기능 구현
  src/main/java/com/nonangbie/auth/jwt/JwtTokenizer.java
  src/main/java/com/nonangbie/member/controller/MemberController.java
  src/main/java/com/nonangbie/member/entity/Member.java
  src/main/java/com/nonangbie/member/service/MemberService.java
Labels: enhancement

#120 fix: #39 데이터 변경
  src/main/resources/data.sql
Labels: enhancement

#121 fix: #43 MemberFood 수정
  src/main/java/com/nonangbie/memberFood/repository/MemberFoodRepository.java
  src/main/java/com/nonangbie/memberFood/service/MemberFoodService.java
Labels: enhancement

#123 feat: #122 이메일 인증 페이지
  src/main/java/com/nonangbie/email/service/EmailVerificationService.java
  src/main/java/com/nonangbie/email/tool/EmailTool.java
  src/main/resources/data.sql
Labels: enhancement

#128 feat:#106 통계창 완성
  src/main/java/com/nonangbie/statistics/controller/StatisticsController.java
  src/main/java/com/nonangbie/statistics/dto/StatisticsDto.java
  src/main/java/com/nonangbie/statistics/mapper/StatisticsMapper.java
  src/main/java/com/nonangbie/statistics/repository/StatisticsRepository.java
  src/main/java/com/nonangbie/statistics/service/StatisticsService.java
Labels: enhancement

#129 feat:#106 통계창 완성
  src/main/java/com/nonangbie/statistics/dto/StatisticsDto.java
  src/main/java/com/nonangbie/statistics/mapper/StatisticsMapper.java
  src/main/java/com/nonangbie/statistics/service/StatisticsService.java
Labels: enhancement

#131 feat: #130 알레르기 구현
  src/main/java/com/nonangbie/AllergyFood/Controller/AllergyFoodController.java
  src/main/java/com/nonangbie/AllergyFood/Dto/AllergyFoodDto.java
  src/main/java/com/nonangbie/AllergyFood/Entity/AllergyFood.java
  src/main/java/com/nonangbie/AllergyFood/Mapper/AllergyFoodMapper.java
  src/main/java/com/nonangbie/AllergyFood/Repository/AllergyFoodRepository.java
  src/main/java/com/nonangbie/AllergyFood/Service/AllergyFoodService.java
  src/main/java/com/nonangbie/exception/ExceptionCode.java
  src/main/java/com/nonangbie/food/entity/Food.java
  src/main/java/com/nonangbie/member/entity/Member.java
Labels: enhancement

#133 fix: #130 알레르기 음식 삭제 수정
  src/main/java/com/nonangbie/AllergyFood/Controller/AllergyFoodController.java
  src/main/java/com/nonangbie/AllergyFood/Service/AllergyFoodService.java
Labels: enhancement

#134 feat:#88 조회 get Method 통합
  src/main/java/com/nonangbie/menu/controller/MenuController.java
  src/main/java/com/nonangbie/menu/entity/Menu.java
  src/main/java/com/nonangbie/menu/repository/MenuRepository.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
Labels: bug

#135 Feat/menu
  src/main/java/com/nonangbie/menu/controller/MenuController.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
  src/main/resources/application.yaml
Labels: enhancement

#136 fix: #75 레시피 수정
  src/main/java/com/nonangbie/menu/controller/MenuController.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
Labels: enhancement

#141 feat:#140 나만의 메뉴 추천 구현
  src/main/java/com/nonangbie/menu/controller/MenuController.java
  src/main/java/com/nonangbie/menu/dto/MenuDto.java
  src/main/java/com/nonangbie/menu/mapper/MenuMapper.java
  src/main/java/com/nonangbie/menu/repository/MenuRepository.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
Labels: enhancement

#144 fix:#140 나만의 메뉴 추천 버그 수정
  src/main/java/com/nonangbie/menu/repository/MenuRepository.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
Labels: bug

#145 fix:#140 나만의 메뉴 추천 버그 수정
  src/main/java/com/nonangbie/menu/service/MenuService.java
Labels: bug

#146 feat:#140 나만의 메뉴 추천 오류 수정
  src/main/java/com/nonangbie/menu/repository/MenuRepository.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
Labels: bug

#148 feat:#140 나만의 메뉴 추천 오류 수정
  src/main/java/com/nonangbie/menu/repository/MenuRepository.java
Labels: bug

#149 feat:#140 나만의 메뉴 추천 오류 수정
  src/main/java/com/nonangbie/menu/repository/MenuRepository.java
  src/main/java/com/nonangbie/menu/service/MenuService.java
Labels: bug

#150 feat:#140 나만의 메뉴 추천 오류 수정
  src/main/java/com/nonangbie/menu/service/MenuService.java
Labels: bug

#152 feat:#151 schema.sql 인덱싱 구현
  src/main/resources/schema.sql
Labels: enhancement

#153 Feat/statistics 통계 초기화 구현
  src/main/java/com/nonangbie/statistics/controller/StatisticsController.java
  src/main/java/com/nonangbie/statistics/service/StatisticsService.java
Labels: enhancement
